quanlyLaptop/quanlyLaptop/Controllers/QuanLyPhieuNhapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using quanlyLaptop.Models;

namespace quanlyLaptop.Controllers
{
    [CustomAuthorize(Roles = "QuanLy,QuanTriWeb")]
    public class QuanLyPhieuNhapController : Controller
    {
        QuanLyBanLapTopEntities db = new QuanLyBanLapTopEntities();

        // GET: QuanLyPhieuNhap
        [HttpGet]
        public ActionResult NhapHang()
        {
            ViewBag.MaNCC = db.NhaCungCaps;
            ViewBag.ListSanPham = db.SanPhams;
            ViewBag.NgayNhap = DateTime.Today;

            return View();
        }
        [HttpPost]
        public ActionResult NhapHang(PhieuNhap model, IEnumerable<ChiTietPhieuNhap> lstModel)
        {

            ViewBag.MaNCC = db.NhaCungCaps;
            ViewBag.ListSanPham = db.SanPhams;
            ViewBag.NgayNhap = DateTime.Today;

            model.NgayNhap = ViewBag.NgayNhap;
            model.DaXoa = false;
            //Sau khi đã ktra hết dl đầu vào

            db.PhieuNhaps.Add(model);
            db.SaveChanges();   //save để lấy MaPN gán cho lst chitietpn
            SanPham sp;
            foreach (var item in lstModel)
            {
                sp = db.SanPhams.Single(n => n.MaSP == item.MaSP);
                sp.SoLuongTon += item.SoLuongNhap;  //update solg tồn

                item.MaPN = model.MaPN; //gán MaPN cho all chitietpn
            }
            
            //db.ChiTietPhieuNhaps.AddRange(lstModel);
            foreach (var item in lstModel)
            {
                db.ChiTietPhieuNhaps.Add(item);
            }
            db.SaveChanges();

            return View();
        }

        [HttpGet]
        public ActionResult DSSPHetHang()
        {
            //ds sp gần hết hàng với số lượng tồn bé hơn hoặc bằng 5
            var lstSP = db.SanPhams.Where(n => n.DaXoa == false && n.SoLuongTon <= 5);
            return View(lstSP);
        }

        [HttpGet]
        public ActionResult NhapHangDon(int? id)
        {
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC");

            if(id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == id);
            if (sp == null)
                return HttpNotFound();
            return View(sp);
        }

        [HttpPost]
        public ActionResult NhapHangDon(PhieuNhap model, ChiTietPhieuNhap ctpn)
        {
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC", model.MaNCC);

            model.NgayNhap = DateTime.Now;
            model.DaXoa = false;
            db.PhieuNhaps.Add(model);
            db.SaveChanges();   //save để lấy MaPN gán cho lst chitietpn

            ctpn.MaPN = model.MaPN;
            SanPham sp = db.SanPhams.Single(n => n.MaSP == ctpn.MaSP);
            sp.SoLuongTon += ctpn.SoLuongNhap;
            db.ChiTietPhieuNhaps.Add(ctpn);
            db.SaveChanges();

            return View(sp);
        }

        //Giải phóng dung lượng biến db, để ở cuối controller
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (db != null)
                    db.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

quanlyLaptop/quanlyLaptop/Views/QuanLyPhieuNhap/DSSPHetHang.cshtml
@model IEnumerable<quanlyLaptop.Models.SanPham>
@{
    ViewBag.Title = "Sản phẩm gần hết hàng";
    Layout = "~/Views/Layout/AdminLayout.cshtml";

    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 10); //khởi tạo control webgird
}

<h2>@ViewBag.Title</h2>
<div class="card">
    <div class="card-body">
        @if (grid != null)
        {
            <div id="list" class="table-responsive">
                @grid.GetHtml(
                tableStyle: "table table-bordered table-hover",
                headerStyle: "",
                footerStyle: "text-center",
                numericLinksCount: 10,
                mode: WebGridPagerModes.All, firstText: "Trang đầu", lastText: "Trang cuối",
                columns: grid.Columns(
                    grid.Column("MaSP", "Mã sản phẩm"),
                    grid.Column("TenSP", "Tên sản phẩm"),
                    grid.Column("HinhAnh", "Hình ảnh", format: p => Html.Raw("<img width=\"100\" height=\"100\" src=\"../Content/HinhAnhSP/" + p.HinhAnh + "\">")),
                    grid.Column(format: p => Html.ActionLink("Nhập hàng", "NhapHangDon", new { id = p.MaSP }))
                    )
                )
            </div>
        }
    </div>
</div>

quanlyLaptop/quanlyLaptop/Views/QuanLyPhieuNhap/NhapHang.cshtml
@using quanlyLaptop.Models
@model PhieuNhap
@{
    ViewBag.Title = "Quản lý phiếu nhập";
    Layout = "~/Views/Layout/AdminLayout.cshtml";

    IEnumerable<NhaCungCap> lstNCC = (IEnumerable<NhaCungCap>)ViewBag.MaNCC;
}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    //script cho datepicker
    $(function () {
        $(".datepicker").datepicker();
    });
</script>

<h2>@ViewBag.Title</h2>
<div class="card">
    <div class="card-body">
        @using (Html.BeginForm())
        {
            <div class="form-group row pb-2">
                <div class=" col-md-6">
                    <label class="col-form-label font-weight-bold ">Nhà cung cấp</label>
                    <select class="MaNCC form-control" name="MaNCC">
                        @foreach (var item in lstNCC)
                        {
                            <option value="@item.MaNCC">@item.TenNCC</option>
                        }
                    </select>
                </div>
                <div class="col-md-6">
                    <label class="col-form-label font-weight-bold ">Ngày nhập</label>
                    <input type="text" class="datepicker form-control"  value="@ViewBag.NgayNhap" />
                </div>
                <div class="clearfix"></div>
            </div>
            @*Phần chi tiết nhập hàng *@
            <table class="tblChiTietPhieuNhap table  table-hover">
                @{IEnumerable<SanPham> lstSanPham = ViewBag.ListSanPham as IEnumerable<SanPham>; }
                @* tạo 1 tr với nd nhập hàng của 1 sp *@

                <tr class="trAppend table-borderless">
                    <td>
                        <select class="ddlSanPham" name="">
                            @foreach (var item in lstSanPham)
                            {
                                <option value="@item.MaSP"> @item.TenSP</option>
                            }
                        </select>
                    </td>
                    <td>
                        <input name="" class="txtDonGia" value="0" />
                    </td>
                    <td>
                        <input name="" class="txtSoLuong" value="0" />
                    </td>
                    <td>
                        <input type="button" class="btnDelete btn btn-danger" style="width: 2em; height:2em;" value="-" />
                    </td>
                </tr>
                <tr class="trFirstChild" data-id="-1">
                    <td class="col-form-label font-weight-bold">Sản phẩm</td>
                    <td class="col-form-label font-weight-bold">Đơn giá nhập</td>
                    <td class="col-form-label font-weight-bold">Số lượng nhập</td>
                    <td></td>
                </tr>
            </table>
            <div class="form-group row">
                <div class="col-md-offset-2 col-sm-6">
                    <input type="button" value="+" class="btn btn-sm btn-success font-weight-bold mr-2" style="width: 3em; height:2em;" id="btnAdd" />
                    <input type="submit" value="Nhập hàng" class="btn btn-sm btn-primary font-weight-bold " id="btnNhapHang" />
                </div>
            </div>
        }
    </div>
</div>
<style>
    .trAppend {
        display:none;
    }
</style>
<script>
    //xử lý sk thêm
    $('#btnAdd').click(function () {
        //Lấy id của tr cuối cùng thuộc thẻ table có class = tblChiTietPhieuNhap
        var id_cuoi = $(".tblChiTietPhieuNhap").find("tr:last-child").attr("data-id");
        i = parseInt(id_cuoi) + 1;

        var tdnoidung = $(".trAppend").html();  //Lấy nội dung phía trong thẻ append
        var trnoidung = "<tr class=\"trAppended\" data-id=\"" + i + "\">" + tdnoidung + "<\tr>"; //Tạo thẻ tr bao ngoài nd
        $(".tblChiTietPhieuNhap").append(trnoidung);    //Lấy thẻ table append vào 1 tr
        loadIDLenThe();
    });
    //xử lý xóa
    $("body").delegate(".btnDelete", "click", function () {
        $(this).closest(".trAppended").remove();
        CapNhapID();
    });

    //krta
    $("#btnNhapHang").click(function () {
        if (kiemTraDonGia() == false)
        {   
            //nếu tồn tại 1 gtri bất kì class dongia kp số thì ko cho submit về server
            return false;   
        }

        if (kiemTraSoLuong() == false) {
            //nếu tồn tại 1 gtri bất kì class dongia kp số thì ko cho submit về server
            return false;
        }
    });

    //xử lý lấy thuộc tính attr từ thẻ tr gán xuống chỉ số phần tử trong thuộc tính name của thẻ input
    function loadIDLenThe() {
        $(".trAppended").each(function () {
            var id = $(this).attr("data-id");   //Lấy thuộc tính data-id của thẻ tr hiện tại
            var nameMaSanPham = "[" + id + "].MaSP";    //tạo ra masp
            var nameDonGiaNhap = "[" + id + "].DonGiaNhap";     //tạo dongia nhap
            var nameSoLuongNhap = "[" + id + "].SoLuongNhap";   //tạo ra solg nhap
            
            $(this).find(".ddlSanPham").attr("name", nameMaSanPham);    //gán name cho dropdownlist
            $(this).find(".txtDonGia").attr("name", nameDonGiaNhap);    //gán name cho dongia nhap
            $(this).find(".txtSoLuong").attr("name", nameSoLuongNhap);  //gán name cho solg nhap
            
        })
    };

    function CapNhapID() {

        //Lấy lại tr1
        var id_cuoi = $(".tblChiTietPhieuNhap").find("trFirstChild").attr("data-id");
        i = parseInt(id_cuoi) + 1;

        $(".trAppended").each(function () {
            var id = i;
            $(this).attr("data-id", i);
            //update lại id khi xóa
            var nameMaSanPham = "[" + id + "].MaSP";    //tạo ra masp
            var nameDonGiaNhap = "[" + id + "].DonGiaNhap";     //tạo dongia nhap
            var nameSoLuongNhap = "[" + id + "].SoLuongNhap";   //tạo ra solg nhap

            $(this).find(".ddlSanPham").attr("name", nameMaSanPham);    //gán name cho dropdownlist
            $(this).find(".txtDonGia").attr("name", nameDonGiaNhap);    //gán name cho dongia nhap
            $(this).find(".txtSoLuong").attr("name", nameSoLuongNhap);  //gán name cho solg nhap
        });
    }

    function kiemTraDonGia() {

        var bl = true;
        //duyệt vòng lặp each
        $(".txtDonGia").each(function () {
            var giatri = $(this).val();
            if (isNaN(giatri) == true) {
                alert("Đơn giá ko hợp lệ!");
                bl = false;
                return bl;
            }
        });
        return bl;
    }

    function kiemTraSoLuong() {

        var bl = true;
        //duyệt vòng lặp each
        $(".txtSoLuong").each(function () {
            var giatri = $(this).val();
            if (isNaN(giatri) == true) {
                alert("Số lượng ko hợp lệ!");
                bl = false;
                return bl;
            }
        });
        return bl;
    }

</script>

quanlyLaptop/quanlyLaptop/Views/QuanLyPhieuNhap/NhapHangDon.cshtml
@model quanlyLaptop.Models.SanPham
@{
    ViewBag.Title = "Sản phẩm gần hết hàng";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>@ViewBag.Title</h2>
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-3">
                <div class="imgSP">
                    <img src="@Url.Content("~/Content/HinhAnhSP/"+Model.HinhAnh)" style="height:150px;width:150px;" />
                </div>
            </div>
            <div class="col-md-9">
                <div class="ttSP">
                    <h3>Sản phẩm: @Model.TenSP</h3>
                    <h3>Hãng sản xuất: @Model.NhaSanXuat.TenNSX</h3>
                    <h3>Loại sản phẩm: @Model.LoaiSanPham.TenLoai</h3>
                    <h3>Số lượng tồn: @Model.SoLuongTon</h3>
                </div>
            </div>
        </div>
        <br />
        <hr />
        <h3>Thông tin nhập hàng</h3>
        <br />
        @using (Html.BeginForm("NhapHangDon", "QuanLyPhieuNhap"))
        {
            @Html.Hidden("MaSP", Model.MaSP)
            <div class="row">
                <div class="col-md-4">
                    @{var lstNCC = (SelectList)ViewBag.MaNCC;}
                    Nhà cung cấp: @Html.DropDownList("MaNCC", lstNCC, new { @class = "MaNCC" })
                </div>
                <div class="col-md-4">
                    Số lượng nhập: @Html.TextBox("SoLuongNhap")
                </div>
                <div class="col-md-4">
                    Đơn giá nhập: @Html.TextBox("DonGiaNhap")
                </div>
                <div class="col-md-4">
                </div>
            </div>
            <div class="clear right mr-3" style="text-align:right;">
                <br />
                <input type="submit" class="btn btn-primary mr-2" value="Nhập hàng" />
                @Html.ActionLink("Trở về", "DSSPHetHang", null, htmlAttributes: new { @class = "btn btn-sm btn-secondary font-weight-bold" })
            </div>
        }
    </div>
</div>