quanlyLaptop/quanlyLaptop/Controllers/QuanLyNhaSXController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using quanlyLaptop.Models;

namespace quanlyLaptop.Controllers
{
    [CustomAuthorize(Roles = "QuanLy,QuanTriWeb")]
    public class QuanLyNhaSXController : Controller
    {
        QuanLyBanLapTopEntities db = new QuanLyBanLapTopEntities();
        // GET: QuanLyNhaSX
        public ActionResult Index()
        {
            return View(db.NhaSanXuats.OrderBy(n=>n.MaNSX));
        }

        [HttpGet]
        public ActionResult TaoMoi()
        {
            return View();
        }

        [HttpPost]
        public ActionResult TaoMoi(NhaSanXuat nsx)
        {
            db.NhaSanXuats.Add(nsx);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult ChinhSua(int? id)
        {
            //lấy sp cần chỉnh sửa
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            NhaSanXuat nsx = db.NhaSanXuats.SingleOrDefault(n => n.MaNSX == id);
            if (nsx == null)
            {
                return HttpNotFound();
            }

            return View(nsx);
        }
        [HttpPost]
        public ActionResult ChinhSua(NhaSanXuat nsx)
        {
            //if(ModelState.IsValid)
            db.Entry(nsx).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Xoa(int? id)
        {
            //lấy sp cần chỉnh sửa
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            NhaSanXuat nsx = db.NhaSanXuats.SingleOrDefault(n => n.MaNSX == id);
            if (nsx == null)
            {
                return HttpNotFound();
            }

            return View(nsx);
        }

        [HttpPost]
        public ActionResult Xoa(int id)
        {
            //lấy sp cần chỉnh sửa
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            NhaSanXuat nsx = db.NhaSanXuats.SingleOrDefault(n => n.MaNSX == id);
            if (nsx == null)
            {
                return HttpNotFound();
            }
            db.NhaSanXuats.Remove(nsx);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        //Giải phóng dung lượng biến db, để ở cuối controller
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (db != null)
                    db.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

quanlyLaptop/quanlyLaptop/Views/QuanLyNhaSX/ChinhSua.cshtml
@model quanlyLaptop.Models.NhaSanXuat
@{
    ViewBag.Title = "Quản lý nhà sản xuất";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h4>@Html.ActionLink("Quản lý nhà sản xuất", "Index") > Chỉnh sửa</h4>
<div class="card">
    <div class="card-body">
        @using (Html.BeginForm("ChinhSua", "QuanLyNhaSX", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.Hidden("MaNSX", Model.MaNSX)

                <div class="form-group row">
                    @Html.LabelFor(model => model.TenNSX, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.TenNSX, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenNSX, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.ThongTin, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.ThongTin, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ThongTin, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row ">
                    <div class="col-sm-4 mt-3">
                        <input type="submit" value="Chỉnh sửa" class="btn btn-sm btn-primary font-weight-bold w-25" />
                        @Html.ActionLink("Trở về", "Index", null, htmlAttributes: new { @class = "btn btn-sm btn-secondary font-weight-bold w-25" })
                    </div>
                </div>
            </div>
        }
    </div>
</div>

quanlyLaptop/quanlyLaptop/Views/QuanLyNhaSX/Index.cshtml
@using quanlyLaptop.Models
@model IEnumerable<NhaSanXuat>
@{
    ViewBag.Title = "Quản lý nhà sản xuất";
    Layout = "~/Views/Layout/AdminLayout.cshtml";

    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 10);
}

<h2>@ViewBag.Title</h2>
<div class="card">
    <div class="card-body">
        <p>
            @Html.ActionLink("Thêm mới", "TaoMoi", null, htmlAttributes: new { @class = "btn btn-sm btn-warning font-weight-bold " })
        </p>
        @if (grid != null)
        {
            <div id="list" class="table-responsive">
                @grid.GetHtml(
                tableStyle: "table table-bordered table-hover",
                headerStyle: "",
                footerStyle: "text-center",
                numericLinksCount: 10,
                mode: WebGridPagerModes.All, firstText: "Trang đầu", lastText: "Trang cuối",
                columns: grid.Columns(
                    grid.Column("MaNSX", "Mã nhà SX"),
                    grid.Column("TenNSX", "Tên nhà SX"),
                    grid.Column("ThongTin", "Thông tin"),
                    grid.Column(format: p => Html.ActionLink("Chỉnh sửa", "ChinhSua", new { id = p.MaNSX })),
                    grid.Column(format: p => Html.ActionLink("Xóa", "Xoa", new { id = p.MaNSX }))
                    )
                )
            </div>
        }
    </div>
</div>

quanlyLaptop/quanlyLaptop/Views/QuanLyNhaSX/TaoMoi.cshtml
@model quanlyLaptop.Models.NhaSanXuat
@{
    ViewBag.Title = "Quản lý nhà sản xuất";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h4>@Html.ActionLink("Quản lý NSX", "Index") > Tạo mới</h4>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Tạo mới nhà sản xuất</h4>
        @using (Html.BeginForm("TaoMoi", "QuanLyNhaSX", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group row">
                    @Html.LabelFor(model => model.TenNSX, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.TenNSX, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenNSX, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.ThongTin, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.ThongTin, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ThongTin, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row ">
                    <div class="col-sm-4 mt-3">
                        <input type="submit" value="Thêm mới" class="btn btn-sm btn-primary font-weight-bold w-25" />
                        @Html.ActionLink("Trở về", "Index", null, htmlAttributes: new { @class = "btn btn-sm btn-secondary font-weight-bold w-25" })
                    </div>
                </div>
            </div>
        }
    </div>
</div>

quanlyLaptop/quanlyLaptop/Views/QuanLyNhaSX/Xoa.cshtml
@model quanlyLaptop.Models.NhaSanXuat
@{
    ViewBag.Title = "Quản lý nhà sản xuất";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<<h4>@Html.ActionLink("Quản lý nhà SX", "Index") > Xóa</h4>
<div class="card shadow">
    <div class="card-body">
        <h4 class="card-title">Thông tin nhà sản xuất</h4>
        <hr />
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.MaNSX)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.MaNSX)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.TenNSX)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.TenNSX)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.ThongTin)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.ThongTin)</div>
        </div>
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-4">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Xóa" class="btn btn-sm btn-primary font-weight-bold w-25" />
                    @Html.ActionLink("Trở về", "Index", null, htmlAttributes: new { @class = "btn btn-sm btn-secondary font-weight-bold w-25" })
                }
            </div>
        </div>

    </div>
</div>