quanlyLaptop/quanlyLaptop/Controllers/PhanQuyenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using quanlyLaptop.Models;

namespace quanlyLaptop.Controllers
{
    [CustomAuthorize(Roles = "QuanTriWeb")]
    public class PhanQuyenController : Controller
    {
        QuanLyBanLapTopEntities db = new QuanLyBanLapTopEntities();
        // GET: PhanQuyen
        public ActionResult Index()
        {
            return View(db.LoaiThanhViens.OrderBy(n => n.TenLoai));
        }

        [HttpGet]
        public ActionResult PhanQuyen(int? id)
        {
            //lấy mã loại tv dựa vào id
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            LoaiThanhVien ltv = db.LoaiThanhViens.SingleOrDefault(n => n.MaLoaiTV == id);
            if (ltv == null)
                return HttpNotFound();
            ViewBag.MaQuyen = db.Quyens; //lấy ds quyền
            ViewBag.LoaiTVQuyen = db.LoaiThanhVien_Quyen.Where(n => n.MaLoaiTV == id);  //lấy ds loại của tv đó
            return View(ltv);
        }
        [HttpPost]
        public ActionResult PhanQuyen(int? MaLTV, IEnumerable<LoaiThanhVien_Quyen> lstPhanQuyen)
        {
            //trường hợp: nếu đã tiến hành phân quyền rồi nhưng muốn phân quyền lại
            //b1: xóa những quyền cũ thuộc loại tv đó
            var lstDaPhanQuyen = db.LoaiThanhVien_Quyen.Where(n => n.MaLoaiTV == MaLTV);
            if (lstDaPhanQuyen.Count() != 0)
            {
                //db.LoaiThanhVien_Quyen.RemoveRange(lstDaPhanQuyen);
                foreach (var item in lstDaPhanQuyen)
                {
                    db.LoaiThanhVien_Quyen.Remove(item);
                }
                db.SaveChanges();
            }
            if(lstDaPhanQuyen != null)
            {
                foreach (var item in lstPhanQuyen)
                {
                    item.MaLoaiTV = int.Parse(MaLTV.ToString());
                    db.LoaiThanhVien_Quyen.Add(item);   //nếu đc check thì add data vào bảng phanquyen
                }
                db.SaveChanges();
            }
            //ktra list ds quyền dc check
            

            return RedirectToAction("Index");
        }
        [AllowAnonymous]
        public ActionResult NotPermission()
        {
            return View();
        }
    }
}

quanlyLaptop/quanlyLaptop/Views/PhanQuyen/Index.cshtml
@using quanlyLaptop.Models
@model IEnumerable<LoaiThanhVien>
@{
    ViewBag.Title = "Phân quyền thành viên";
    Layout = "~/Views/Layout/AdminLayout.cshtml";

    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 10);
}

<h2>@ViewBag.Title</h2>
<div class="card">
    <div class="card-body">
        @if (grid != null)
        {
            <div id="list" class="table-responsive">
                @grid.GetHtml(
                tableStyle: "table table-bordered table-hover",
                headerStyle: "",
                footerStyle: "text-center",
                numericLinksCount: 10,
                mode: WebGridPagerModes.All, firstText: "Trang đầu", lastText: "Trang cuối",
                columns: grid.Columns(
                    grid.Column("MaLoaiTV", "Mã Loại TV"),
                    grid.Column("TenLoai", "Tên loại"),                  
                    grid.Column(format: p => Html.ActionLink("Phân quyền", "PhanQuyen", new { id = p.MaLoaiTV }))
                    )
                )
            </div>
        }
    </div>
</div>

quanlyLaptop/quanlyLaptop/Views/PhanQuyen/NotPermission.cshtml
@{
    ViewBag.Title = "NotPermission";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Tài khoản của bạn không đủ quyền truy cập chức năng này</h2>

quanlyLaptop/quanlyLaptop/Views/PhanQuyen/PhanQuyen.cshtml
@using quanlyLaptop.Models
@model LoaiThanhVien
@{
    ViewBag.Title = "Phân quyền thành viên";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h4>@Html.ActionLink("Phân quyền thành viên", "Index") > Phân quyền</h4>
<div class="card">
    <div class="card-body">
        <h2>Loại thành viên: @Model.TenLoai</h2>
        @{
            IEnumerable<Quyen> lstQuyen = (IEnumerable<Quyen>)ViewBag.MaQuyen;
            IEnumerable<LoaiThanhVien_Quyen> lstLTVQuyen = (IEnumerable<LoaiThanhVien_Quyen>)ViewBag.LoaiTVQuyen;
        }
        @using (Html.BeginForm())
        {
            @Html.Hidden("MaLTV", Model.MaLoaiTV)
            if (lstLTVQuyen != null)
            {
                for (int j = 0; j < lstQuyen.Count(); j++)
                {
                    int k = 0;  //tạo biến k làm biến đếm để duyệt vòng lặp của bảng quyền xem nếu loại tv nào có mã quyền ứng vs quyền
                    for (int i = 0; i < lstLTVQuyen.Count(); i++)
                    {   //ss giữa item trong bảng quyen và item trong bảng loaitvquyen vs MaQuyen
                        if (lstQuyen.ElementAt(j).MaQuyen == lstLTVQuyen.ElementAt(i).MaQuyen)
                        {
                            k++;
                            break;
                        }
                    }
                    if (k != 0)
                    {
                        <div class="col-md-4" style="font-size:15pt;">
                            <input class="ckb_Click" checked="checked" type="checkbox" style="height:1em; width:1em;" name="@Url.Content("["+j+"].MaQuyen")" value="@lstQuyen.ElementAt(j).MaQuyen" />
                            @lstQuyen.ElementAt(j).MaQuyen
                        </div>
                    }
                    else
                    {
                        <div class="col-md-4" style="font-size:15pt;">
                            <input class="ckb_Click" type="checkbox" style="height:1em; width:1em;" name="@Url.Content("["+j+"].MaQuyen")" value="@lstQuyen.ElementAt(j).MaQuyen" />
                            @lstQuyen.ElementAt(j).TenQuyen
                        </div>
                    }
                    k = 0;
                }
            }
            else
            {   //đối vs loại tv chưa phân quyền
                for (int i = 0; i < lstQuyen.Count(); i++)
                {
                    <div class="col-md-4" style="font-size:12pt;">
                        <input class="ckb_Click" type="checkbox" style="height:1em; width:1em;" name="@Url.Content("["+i+"].MaQuyen")" value="@lstQuyen.ElementAt(i).MaQuyen" />
                        @lstQuyen.ElementAt(i).TenQuyen
                    </div>
                }
            }
            <div class="form-group row mt-3">
                <div class="col-sm-4">
                    <input type="submit" value="Thực hiện" class="btn btn-sm btn-primary font-weight-bold w-25" />
                    @Html.ActionLink("Trở về", "Index", null, htmlAttributes: new { @class = "btn btn-sm btn-secondary font-weight-bold w-25" })
                </div>
            </div>
        }
    </div>
</div>
@* Hàm jquery duyệt lại checkbox đã đc check *@
<script>
    $(".ckb_Click").click(function () {
        i = 0;
        $(".ckb_Click").each(function () {
            if ($(this).is(':checked'))
            {
                $(this).attr("name", "[" + i + "].MaQuyen");
                i++
            }
        })
    })
</script>